@startuml Caso-hotel

class Listado_clientes {
  - clientes: List<Cliente>
  + agregar_cliente(cliente: Cliente)
  + eliminar_cliente(cliente: Cliente)
  + buscar_cliente(dni: String, nombre:String): Cliente
}

class Cliente {
  - nombre: String
  - apellido: String
  - dni: String
  - telefono: String
  - email: String
  - direccion: String
  - fecha_Nacimiento: Date
  + tipo_cliente: String
}

class Habituales {
  - descuento: double
}

class Esporadicos {
  - descuento: double
}

Listado_clientes *-- Cliente
Cliente <|-- Habituales
Cliente <|-- Esporadicos

class listado_habitaciones {
  - habitaciones: List<Habitacion>
  + agregar_habitacion(habitacion: Habitacion)
  + eliminar_habitacion(habitacion: Habitacion)
  + buscar_habitacion(numero: String): Habitacion
}

class Habitacion {
  - numero: String
  - tipo: String
  - precio: double
  - estado: String
}

listado_habitaciones *-- Habitacion

class listado_reservas {
  - reservas: List<Reserva>
  + agregar_reserva(reserva: Reserva)
  + eliminar_reserva(reserva: Reserva)
  + buscar_reserva(numero: String): Reserva
}

class Reserva {
  - cliente: Cliente
  - habitacion: Habitacion
  - fecha_entrada: Date
  - fecha_salida: Date
  - descuento: double
  - estado: String
  + calcular_precio_total(): double
}

listado_reservas *-- Reserva

class Listado_tipo_cliente {
  + modificar_tipo_cliente(tipo_cliente: String)
  + agregar_tipo_cliente(tipo_cliente: String)
  + eliminar_tipo_cliente(tipo_cliente: String)
}

Habituales *-- Listado_tipo_cliente
Esporadicos *-- Listado_tipo_cliente

@enduml